# Site settings
title: Peeters IT Consultancy
email: jeroen@peetersweb.nl
url: https://example.github.io
description: "Passionate Software Engineer"
keywords: "software engineering, software development"
skills: "Software Engineering - Quality Assurance - Agile Process"
meta_author: Peeters Jeroen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jeroen Peeters
  location: Region
  social: Around the Web
  available_as: Available as 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jeroenp/
  - title: twitter
    url: http://twitter.com/jeroenpeeters
  - title: stack-overflow
    url: https://stackoverflow.com/users/1132644/jeroen-peeters?tab=profile
  - title: github
    url: http://github.com/jeroenpeeters

# Postal address (add as many lines as necessary)
address:
  - line: Den Haag
  - line: Amsterdam
  - line: Rotterdam

# Credits content
available_as: 
  - title: Senior Software Engineer
  - title: Technical Lead
  - title: Solution Architect

# Build settings
markdown: kramdown
permalink: pretty
